services:
  - type: web
    name: rvl-site
    env: python
    buildCommand: python -m pip install -r requirements.txt && python manage.py migrate && python manage.py seed && python manage.py collectstatic --noinput
    startCommand: gunicorn rvl_site.wsgi:application --log-file -
    envVars:
      - key: DJANGO_DEBUG
        value: "False"
      - key: DJANGO_ALLOWED_HOSTS
        value: ".onrender.com"
      - key: DJANGO_CSRF_TRUSTED
        value: "https://*.onrender.com"
